---
title: "Data Wrangling"
author: "Gabriel Storch"
---
# Loading of libraries
```{r}
suppressWarnings({
library(tidyverse)
library(vroom)
library(glue)
})
```

# Loading the data

```{r}
data_folder <- "03_data/Patent_data_reduced/"

col_types_patent <- list(
  id = col_character(),
  date = col_date("%Y-%m-%d"),
  num_claims = col_double()
)

col_types_patent_assignee <- list(patent_id=col_character(),
                                  assignee_id=col_character())

col_types_assignee <- list(id=col_character(),
                               type=col_character(),
                               organization=col_character())


col_types_uspc <- list(patent_id=col_character(),
                       mainclass_id=col_character(),
                       sequence=col_double())

patent_tbl <- vroom(
            file       = glue("{data_folder}patent.tsv"), 
            delim      = "\t", 
            col_types  = col_types_patent,
            na         = c("", "NA", "NULL")
        )

patent_assignee_tbl <- vroom(
            file       = glue("{data_folder}patent_assignee.tsv"), 
            delim      = "\t", 
            col_types  = col_types_patent_assignee,
            na         = c("", "NA", "NULL")
        )

assignee_tbl <- vroom(
            file       = glue("{data_folder}assignee.tsv"), 
            delim      = "\t", 
            col_types  = col_types_assignee,
            na         = c("", "NA", "NULL")
        )

uspc_tbl <- vroom(
            file       = glue("{data_folder}uspc.tsv"), 
            delim      = "\t", 
            col_types  = col_types_uspc,
            na         = c("", "NA", "NULL")
        )

```

# Top Ten US companies (patent-wise) 2014

```{r}

patent_tbl <- patent_tbl |> mutate(date=month(date)) |> rename(patent_id=id)

us_assignee_tbl <- assignee_tbl[assignee_tbl$type == "2",] |> rename(assignee_id = id)

us_patent_assignee_tbl <- patent_assignee_tbl |>
  inner_join(us_assignee_tbl, by="assignee_id")

grouped_us_patent_assignee_tbl <- us_patent_assignee_tbl |>
  group_by(assignee_id) |>
  summarise(num_patents=n()) |>
  arrange(desc(num_patents))


ten_us_companies_with_most_patents <- inner_join(head(grouped_us_patent_assignee_tbl, 10), us_assignee_tbl, by="assignee_id")[c("organization", "num_patents")]

ten_us_companies_with_most_patents

```

# Top Ten US companies (patent-wise) in August of 2014

```{r}
patent_tbl_august <- patent_tbl[patent_tbl$date == 8,]

ten_us_companies_with_most_patents_august <- us_patent_assignee_tbl |>
  inner_join(patent_tbl_august, by="patent_id") |>
  group_by(organization) |> 
  summarize(num_patents=n()) |> # counts rows 
  arrange(desc(num_patents)) |>
  head(10)

ten_us_companies_with_most_patents_august
```

# Five most common USPCs for the global Top Ten companies (patent-wise) of 2014

```{r}
# type 2 and 3 are companies
company_assignee_tbl <- assignee_tbl[assignee_tbl$type == "2" | assignee_tbl$type == "3",] |> rename(assignee_id = id)

# global top ten for patents
global_top_ten_frame <- company_assignee_tbl |> 
  inner_join(patent_assignee_tbl, by="assignee_id") |> 
  group_by(assignee_id) |> 
  summarize(num_patents=n()) |> 
  arrange(desc(num_patents)) |> 
  head(10)

# mapping company to uspc

company_patent_uspc_tbl <- company_assignee_tbl |> 
  inner_join(patent_assignee_tbl, join_by(assignee_id)) |> 
  inner_join(uspc_tbl, by="patent_id", relationship = "many-to-many")


# for creation of final result frame
company_uspc<- tibble(
  name = character(),
  fst = character(),
  snd = character(),
  third =  character(),
  fourth =  character(),
  fifth =  character()
)

# for each company in the top ten, get the 5 most common USPCs
for (company in global_top_ten_frame$assignee_id) {
  top_uspc_codes <- company_patent_uspc_tbl[company_patent_uspc_tbl$assignee_id == company,] |>
    group_by(mainclass_id) |> 
    summarize(count = n()) |> 
    arrange(desc(count)) |> 
    head(5)
  
  comp_name <- head(company_assignee_tbl[company_assignee_tbl$assignee_id==company,], 1)$organization
  cls <- top_uspc_codes$mainclass_id

  company_uspc <- company_uspc |> add_row(name=comp_name,
                          fst=cls[1],
                          snd = cls[2],
                          third =  cls[3],
                          fourth =  cls[4],
                          fifth =  cls[5])
}
# Top Five USPCs for each of the global Top Ten Companies
company_uspc

```


# And the global Top Five tech sectors
``` {r}
top_uspc_codes <- company_patent_uspc_tbl[company_patent_uspc_tbl$assignee_id %in% global_top_ten_frame$assignee_id,] |>
    group_by(mainclass_id) |> 
    summarize(count = n()) |> 
    arrange(desc(count)) |> 
    head(5)

#Globally most innovative tech sectors
top_uspc_codes$mainclass_id

```

